(import (scheme base) (scheme process-context) (srfi 64))
(test-begin "lists")
(test-group "g1" (test-eqv "a" 1 1))
(test-group "g2" (test-eqv "a" 1 1))
(test-group "g3" (test-eqv "a" 1 1))
(test-group "g4" (test-eqv "a" 1 1))
(test-group "g5" (test-eqv "a" 1 1))
(test-group "g6" (test-eqv "a" 1 1))
(test-group "g7" (test-eqv "a" 1 1))
(test-group "member" (test-equal "m" '(3) '(3)))
(test-end "lists")
