#!/usr/bin/env bash
# Phase 4 language/library parity: audit portable lib/srfi/*.sld imports.
#
# For each top-level lib/srfi/N.sld (skips subdirectories), attempts a
# minimal `(import (srfi N))` against the built binary and records
# pass/fail. Chaaya has no `-e` eval flag; scripts are fed via stdin
# (see docs/dev/cli.md: "No file + non-TTY stdin -> evaluate stdin as a
# script"), so each probe is piped in.
#
# Usage: scripts/audit-srfi-imports.sh [output-report.md]
set -euo pipefail

repo_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
chaaya_bin="${repo_root}/build/chaaya"
srfi_dir="${repo_root}/lib/srfi"
report="${1:-${repo_root}/docs/dev/srfi-import-audit.md}"

if [[ ! -x "${chaaya_bin}" ]]; then
  echo "error: chaaya binary not found at ${chaaya_bin}; run 'make' first." >&2
  exit 1
fi

pass_list=()
fail_entries=()

shopt -s nullglob
for sld in "${srfi_dir}"/*.sld; do
  n="$(basename "${sld}" .sld)"
  probe="(import (srfi ${n}))"
  if out="$(printf '%s\n' "${probe}" | "${chaaya_bin}" --lib-path "${repo_root}/lib" 2>&1)"; then
    pass_list+=("${n}")
  else
    first_line="$(printf '%s\n' "${out}" | head -n1)"
    fail_entries+=("${n}|${first_line}")
  fi
done
shopt -u nullglob

total=$(( ${#pass_list[@]} + ${#fail_entries[@]} ))

{
  echo "# SRFI import audit (portable \`lib/srfi/*.sld\`)"
  echo
  echo "Generated by \`scripts/audit-srfi-imports.sh\`. Probes each top-level"
  echo "\`lib/srfi/N.sld\` with a minimal \`(import (srfi N))\` via"
  echo "\`./build/chaaya --lib-path ./lib\` (script fed on stdin; Chaaya has no"
  echo "\`-e\` flag)."
  echo
  echo "Date: $(date -u +%Y-%m-%d)"
  echo
  echo "## Summary"
  echo
  echo "- Total top-level \`.sld\` files probed: ${total}"
  echo "- Pass: ${#pass_list[@]}"
  echo "- Fail: ${#fail_entries[@]}"
  echo
  echo "## Note on built-in vs. portable SRFI shadowing"
  echo
  echo "Several SRFI numbers (e.g. 1, 13, 69) have **both** a native built-in"
  echo "implementation registered in \`ch_vm_register_primitives\` /"
  echo "\`library_builtin.c\` **and** a portable \`.sld\` under \`lib/srfi/\`. This is"
  echo "intentional: \`ch_ensure_library\` (\`src/library.c\`) looks up"
  echo "\`vm->libraries\` (built-ins) first and only falls back to resolving and"
  echo "loading a \`.sld\` from \`--lib-path\` when no built-in registration exists."
  echo "The portable shadow files exist for documentation/reference and for"
  echo "hosts that don't register the built-in, but built-ins always win when"
  echo "both are present. Do not delete the portable shadows."
  echo
  echo "## Fixes applied (2026-08-02 audit pass)"
  echo
  echo "A batch of primitives that were listed in \`library_builtin.c\`'s export"
  echo "tables (or otherwise commonly needed) but never actually implemented"
  echo "were added, flipping five imports from fail to pass"
  echo "(\`srfi 51\`, \`srfi 116\`, \`srfi 140\`, \`srfi 152\`, \`srfi 263\`):"
  echo
  echo "- \`src/prim_srfi1.c\` (\`(srfi 1)\`): \`fold-right\`, \`remove\`, \`find\`,"
  echo "  \`any\`, \`every\`, \`alist-cons\`, \`alist-delete\`, \`delete\`,"
  echo "  \`lset-adjoin\`, \`lset-union\`, \`append-reverse\`."
  echo "- \`src/prim_srfi13.c\` (\`(srfi 13)\`): \`string-every\`, \`string-any\`,"
  echo "  \`string-count\`, \`string-filter\`, \`string-delete\` (procedure"
  echo "  predicates only, matching this file's existing \`string-index\` /"
  echo "  \`string-skip\` simplification -- no char-set support yet). Also added"
  echo "  to \`srfi13_exports\` in \`src/library_builtin.c\`, which previously"
  echo "  omitted these five names entirely."
  echo "- \`src/prim_srfi133.c\` (\`(srfi 133)\`): \`vector-map!\`,"
  echo "  \`vector-fold-right\` (both already listed in \`srfi133_exports\` but"
  echo "  never registered)."
  echo
  echo "## Remaining failure categories"
  echo
  echo "The rest of the failures below fall into a few buckets that are each"
  echo "bigger than a \"missing primitive\" fix:"
  echo
  echo "1. **Native sub-library never ported from Kaappi (Zig) to Chaaya (C)** --"
  echo "   \`library not found: srfi.NNN.primitives\` (131, 136, 137, 150, 181,"
  echo "   237, 240, 57) and \`srfi.160.primitives\` (4, 63, 66, 74, 231). These"
  echo "   \`.sld\` files were carried over from Kaappi's tree and depend on"
  echo "   substantial native features Chaaya doesn't have yet: a record-type-"
  echo "   descriptor engine (237/57/131/136/150), a \`NumericVector\` heap type"
  echo "   (160, and 4/63/66/74 which sit on top of it), custom ports (181),"
  echo "   and syntax-parameter/explicit-renaming macros (211). Each is a"
  echo "   standalone feature project, not a primitive-list gap."
  echo "2. **Kaappi-only helper libraries** -- \`library not found: kaappi.sysinfo\`"
  echo "   (59, 112, 193) and \`kaappi.primitives\` (271): these \`.sld\` files"
  echo "   assume Kaappi-specific runtime introspection that has no Chaaya"
  echo "   equivalent."
  echo "3. **Exporting a special form as a library binding** -- \`define-library:"
  echo "   exported binding 'X' is undefined\` for \`cond-expand\` (0),"
  echo "   \`let-values\`/\`let*-values\` (11, 234), \`case-lambda\` (16), \`guard\`"
  echo "   (34), \`delay\` (45), \`either\` (189, a normal export that fails"
  echo "   because the library also exports \`values->maybe\`'s sibling forms --"
  echo "   see the file for the actual name collision), \`define-property\` (213,"
  echo "   an engine-level compiler form), and \`_\` (257, a pattern-matcher"
  echo "   literal). Compiler special forms and syntax-only bindings aren't"
  echo "   ordinary global values, so a portable library can't easily"
  echo "   re-export them; needs expander/library support for syntax exports,"
  echo "   not a VM primitive."
  echo "4. **Importing a special form as a value** -- \`import only/except:"
  echo "   identifier 'X' not found in import set\` for \`define-syntax\`/"
  echo "   \`syntax-rules\` (139, 147, 148, 149, 46), \`define-values\` (244),"
  echo "   \`guard\` (248), and \`let\` (71): same root cause as #3, from the"
  echo "   importing side."
  echo "5. **Needs deeper triage** -- \`wrong number of arguments\` at library"
  echo "   load time (44, 113, 146, 162, 167, 168, 228) and a bare runtime"
  echo "   \`error\` during load (36); likely a \`define-record-type\` /"
  echo "   \`define-condition-type\` arity mismatch worth its own investigation."
  echo
  echo "## Failures"
  echo
  if [[ "${#fail_entries[@]}" -eq 0 ]]; then
    echo "None."
  else
    echo "| SRFI | First line of error |"
    echo "|------|----------------------|"
    for entry in "${fail_entries[@]}"; do
      n="${entry%%|*}"
      msg="${entry#*|}"
      # Escape pipe characters for markdown table cells.
      msg="${msg//|/\\|}"
      echo "| ${n} | ${msg} |"
    done
  fi
  echo
  echo "## Passing"
  echo
  if [[ "${#pass_list[@]}" -eq 0 ]]; then
    echo "None."
  else
    printf '%s' "srfi ${pass_list[0]}"
    for n in "${pass_list[@]:1}"; do
      printf ', %s' "srfi ${n}"
    done
    echo
  fi
} > "${report}"

echo "Report written to ${report}"
echo "Pass: ${#pass_list[@]}  Fail: ${#fail_entries[@]}  Total: ${total}"
